version: '3.8'

services:
  chat:
    container_name: chat
    build: .
    volumes:
    - ./:/usr/src/app/
    - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    command: ["yarn", "serve"]
